# Generated by Django 2.1.1 on 2018-09-28 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automovil',
            name='marca',
        ),
        migrations.DeleteModel(
            name='Automovil',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
    ]
