# Generated by Django 2.1.1 on 2018-10-12 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180928_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automovil',
            options={'permissions': (('can_add', 'puede agregar autos'), ('can_delete', 'puede eliminar autos'), ('can_modify', 'puede modifica autos')), 'verbose_name': 'Automovil', 'verbose_name_plural': 'Automoviles'},
        ),
    ]
