# Generated by Django 2.1.1 on 2018-10-12 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181012_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automovil',
            options={'permissions': (('auto_can_add', 'puede agregar autos'), ('auto_can_delete', 'puede eliminar autos'), ('auto_can_modify', 'puede modifica autos')), 'verbose_name': 'Automovil', 'verbose_name_plural': 'Automoviles'},
        ),
    ]
